#include <erl/field/Field2DEvolverSettings.h>

using namespace erl;

Field2DEvolverSettings::Field2DEvolverSettings()
: _minInitWeight(-0.5f),
_maxInitWeight(0.5f),
_updateCrossoverAverageChance(0.2f),
_neAddNodeChance(0.07f),
_neAddConnectionChance(0.14f),
_neWeightPerturbationChance(0.08f),
_neMaxWeightPerturbation(0.25f),
_neChangeFunctionChance(0.04f),
_neWeightFactor(0.5f),
_neDisjointFactor(1.0f),
_addConnectionResponseChance(0.03f),
_addNodeOutputChance(0.03f),
_addGasChance(0.03f),
_connectionReponseDifferenceFactor(5.0f),
_nodeOutputSizeDifferenceFactor(5.0f),
_gasCountDifferenceFactor(5.0f),
_averageInitChance(0.15f),
_initPerturbationChance(0.05f),
_maxInitPerturbation(0.25f),
_minInitInputStrengthScalar(10.0f),
_maxInitInputStrengthScalar(20.0f),
_averageInputStrengthScalarChance(0.1f),
_mutateInputStrengthChance(0.05f),
_maxInputStrengthPerturbation(3.0f),
_inputStrengthDifferenceFactor(1.0f),
_minInitConnectionStrengthScalar(2.0f),
_maxInitConnectionStrengthScalar(5.0f),
_averageConnectionStrengthScalarChance(0.2f),
_mutateConnectionStrengthChance(0.05f),
_maxConnectionStrengthPerturbation(0.5f),
_connectionStrengthDifferenceFactor(1.0f),
_minInitNodeOutputStrengthScalar(2.0f),
_maxInitNodeOutputStrengthScalar(6.0f),
_averageNodeOutputStrengthScalarChance(0.2f),
_mutateNodeOutputStrengthChance(0.05f),
_maxNodeOutputStrengthPerturbation(1.0f),
_nodeOutputStrengthDifferenceFactor(1.0f)
{}